{% set name = "py-cord" %}
{% set version = "2.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 36064f225f2c7bbddfe542d5ed581f2a5744f618e039093cf7cd2659a58bc79b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=62.6,<70
    - setuptools-scm >=6.2,<8
  run:
    - python >=3.8
    - aiohttp >=3.6.0,<4.0
    - typing_extensions >=4,<5

test:
  imports:
    - discord
    - discord.types
    - discord.sinks
    - discord.ui
    - discord.webhook
    - discord.commands
    - discord.ext.commands
    - discord.ext.tasks
    - discord.ext.pages
    - discord.ext.bridge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Pycord-Development/pycord
  doc_url: https://docs.pycord.dev/
  summary: A Python wrapper for the Discord API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
