{% set name = "py-cord" %}
{% set version = "2.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 100935f37e77ba8ac1e3eff0b180e6d69bcac083de81d4c83d42327d9a2eddee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=62.6,<70
    - setuptools-scm >=6.2,<8
  run:
    - python >={{ python_min }}
    - aiohttp >=3.6.0,<4.0
    - typing_extensions >=4,<5

test:
  imports:
    - discord
    - discord.types
    - discord.sinks
    - discord.ui
    - discord.webhook
    - discord.commands
    - discord.ext.commands
    - discord.ext.tasks
    - discord.ext.pages
    - discord.ext.bridge
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Pycord-Development/pycord
  doc_url: https://docs.pycord.dev/
  summary: A Python wrapper for the Discord API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
