{% set name = "py-cord" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-cord-{{ version }}.tar.gz
  sha256: faf08af5da5eac2ed3d1c8a43d8307d5a1e3f01602def283330c9d2cde0b1162

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=62.6,<70
    - setuptools-scm >=6.2,<8
  run:
    - python >=3.8
    - aiohttp >=3.6.0,<4.0
    - typing_extensions >=4,<5

test:
  imports:
    - discord
    - discord.types
    - discord.sinks
    - discord.ui
    - discord.webhook
    - discord.commands
    - discord.ext.commands
    - discord.ext.tasks
    - discord.ext.pages
    - discord.ext.bridge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Pycord-Development/pycord
  doc_url: https://docs.pycord.dev/
  summary: A Python wrapper for the Discord API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
