schema_version: 1

context:
  name: py-cord
  version: "2.7.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 100935f37e77ba8ac1e3eff0b180e6d69bcac083de81d4c83d42327d9a2eddee

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=77.0.3,<=80.9.0
    - setuptools-scm >=9.2,<=9.2.2
  run:
    - python >=${{ python_min }}
    - aiohttp >=3.6.0,<4.0
    - typing_extensions >=4.12.0,<5

tests:
  - python:
      imports:
        - discord
        - discord.types
        - discord.sinks
        - discord.ui
        - discord.webhook
        - discord.commands
        - discord.ext.commands
        - discord.ext.tasks
        - discord.ext.pages
        - discord.ext.bridge
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A Python wrapper for the Discord API
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Pycord-Development/pycord
  documentation: https://docs.pycord.dev/

extra:
  recipe-maintainers:
    - thewchan
